name: Workflow CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: ${{ github.workspace }}/MLProject/mlruns

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Setup Python 3.12.7 (to match conda.yaml)
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      
      # Check Env Variables
      - name: Check Env
        run: |
          echo $CSV_URL
          
      # Install Python dependencies for the MLflow run
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==3.1.1 scikit-learn==1.7.0 pandas numpy joblib dagshub
          
      # Run as a mlflow project
      - name: Run mlflow project
        working-directory: ./MLProject
        run: mlflow run . --env-manager=local
      
      # Get latest run_id
      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td $MLFLOW_TRACKING_URI/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"
          
      - name: Install Python dependencies
        run: |
          pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client
        
      # - name: Upload to Google Drive
        # env:
          # GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}  # Mengambil kredensial dari GitHub Secrets
          # GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}  # Mengambil kredensial dari GitHub Secrets
        # run: |
          # python MLProject/upload_to_gdrive.py

          
      # Build Docker Model
      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "cc" 

      # Login to Docker Hub
      # - name: Log in to Docker Hub
        # uses: docker/login-action@v2
        # with:
          # username: ${{ secrets.DOCKER_HUB_USERNAME }}
          # password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Tag the Docker image
      # - name: Tag Docker Image
        # run: |
          # docker tag cc ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest

      # Push Docker image to Docker Hub
      # - name: Push Docker Image
        # run: |
          # docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest
