name: Workflow CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: ${{ github.workspace }}/MLProject/mlruns

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Setup Python 3.12.7 (to match conda.yaml)
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      
      # Check Env Variables
      - name: Check Env
        run: |
          echo $CSV_URL
          
      # Install Python dependencies for the MLflow run
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==3.1.1 scikit-learn==1.7.0 pandas numpy joblib dagshub
          
      # Run as a mlflow project
      - name: Run mlflow project
        working-directory: ./MLProject
        run: mlflow run . --env-manager=local
      
      # Get latest run_id
      - name: Get latest MLflow run_id
        run: |
          LATEST_RUN_DIR=$(ls -td $MLFLOW_TRACKING_URI/0/*/ | head -n 1)
          RUN_ID=$(basename $LATEST_RUN_DIR)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      # Upload MLflow artifacts
      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: ${{ env.MLFLOW_TRACKING_URI }}
          
      # Build Docker Model
      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "cc" 

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Tag and Push Docker image to Docker Hub
      - name: Tag and Push Docker Image
        run: |
          docker tag cc ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest
